\documentclass{article}
\usepackage[sc]{mathpazo}
\usepackage[T1]{fontenc}
\usepackage{geometry}
\usepackage[utf8]{inputenc}
\usepackage{amsmath}
\usepackage{float}
\usepackage{caption}
\usepackage{subcaption}
\usepackage[demo]{graphicx}
\usepackage{booktabs}
\geometry{verbose,tmargin=2.5cm,bmargin=2.5cm,lmargin=2.5cm,rmargin=2.5cm}
\setcounter{secnumdepth}{2}
\setcounter{tocdepth}{2}
\usepackage{url}
\usepackage[unicode=true,pdfusetitle,
 bookmarks=true,bookmarksnumbered=true,bookmarksopen=true,bookmarksopenlevel=2,
 breaklinks=false,pdfborder={0 0 1},backref=false,colorlinks=false]
 {hyperref}
\hypersetup{
 pdfstartview={XYZ null null 1}}
\usepackage{breakurl}
\usepackage{array}
\newcommand\Mark[1]{\textsuperscript#1}
\renewcommand{\hlcom}[1]{\textcolor[rgb]{0.678,0.584,0.686}{\textbf{#1}}}%


\begin{document}


<<setup, include=FALSE, cache=FALSE>>=
# set global chunk options
# for figures
opts_chunk$set(fig.path='figs/', fig.align='center', fig.show='hold',
               dev='CairoPDF', out.width='.4\\linewidth')
# replacing "=" into "->" to make it R thing
options(replace.assign=TRUE,width=90)
# caching chunks
opts_chunk$set(cache.extra = R.version,cache.path='cache/')
opts_chunk$set(cache.extra = rand_seed)
@
\begingroup

\centering
{\LARGE Functional Analysis of CebpE Dimer \\[1.5em]
\large Ricky Lim\Mark{1}, Samuel Collombet\Mark{2}, Agus Salim\Mark{3}, Touati Benoukraf\Mark{1}}\\[1em]
\begin{tabular}{*{3}{>{\centering}p{.25\textwidth}}}
    \Mark{1}Cancer Science Institute of Singapore, National University of Singapore&\Mark{2}Institut de Biologie de l'Ecole Normale Superieur de Paris& \Mark{3}Department of Mathematics and Statistics& \tabularnewline
\url{benoukraf@nus.edu.sg}
\end{tabular}\par
\endgroup

\section{Codes}
<<Rcode>>=
library(plyr)
library(xtable)
library(ggplot2)
library(reshape)
work_dir='/home/ricky/Rlim/ChromatinConformation/DimerCebpMotif/'
#work_dir = '/Users/RickyLim/Desktop/CebpE/'

Barplot_Chunk <- function(dataTable, N, vars, output_n, ylabel, TERM=TRUE){

    #############################################################################
    # Returns N barplots that chunks the dataTable                              #
    #                                                                           #
    # dataTable looks like (tab-delimited)                                      #
    #                                                                           #
    # Term Function Percent.Homo Fold.Homo Bonferroni.Homo ..                   #
    #  1    binding  1.5          1.44     1.075                                #
    #                                                                           #
    #                                                                           #
    #                                                                           #
    # > Barplot_Chunk(dataTable=homohetero_GO, N=12,                            #    
    #                    vars=c('Term', 'Benjamini.Homo', 'Benjamini.Hetero'),  #    
    #                    ylabel='- Log(P Value)',                               #    
    #                    output_n= 'figs/homohetero_BenjaminiGO')               #    
    #                                                                           #
    #############################################################################

    chunks <- split(dataTable,                                         
                    (as.numeric(rownames(dataTable))-1) %/% N )        
    for (i in 1: length(chunks)){                                      
        chunk.m <- melt(chunks[[i]][, vars], id.vars=1)                
                                                                        
        if (TERM){
            p <- ggplot(chunk.m, aes(x=Term, y=value, fill=variable)) +    
                    geom_bar(stat='identity', position='dodge') +          
                    theme(axis.text.x = element_text(angle=90, hjust=1))+  
                    ylab(ylabel)+xlab('')                                  
            }
        else{
        #p <- ggplot(chunk.m, aes(x=Term, y=value, fill=variable)) +    
            p <- ggplot(chunk.m, aes(x=Function, y=value, fill=variable)) +    
                    geom_bar(stat='identity', position='dodge') +          
                    theme(axis.text.x = element_text(angle=90, hjust=1))+  
                    ylab(ylabel)+xlab('')                                  
        }
        p                                                              
        ggsave(paste0(output_n,'_', i, '.pdf'))                        
    }                                                                  
}                                                                      

@

\section{DavidGOTerm}
<<GODavid, cache=TRUE>>=
homodimer_GO <- read.table(paste0(work_dir,
                    'CebpE/Output/ChipMeme/Motif/',
                    'homo_GOChart_Percent_Fold_Bonferroni_Benjamini.txt'),
                    header=FALSE,sep='\t')

colnames(homodimer_GO) <- c('Term', 'Function',
                            'Percent', 'Fold',
                            'Bonferroni','Benjamini')
homodimer_GO[, 'Benjamini'] <- (-log(homodimer_GO$Benjamini))
homodimer_GO[, 'Bonferroni'] <- (-log(homodimer_GO$Bonferroni))
head(homodimer_GO)

heterodimer_GO <- read.table(paste0(work_dir,
                    'CebpE/Output/ChipMeme/Motif/',
                    'hetero_GOChart_Percent_Fold_Bonferroni_Benjamini.txt'),
                    header=FALSE,sep='\t')
colnames(heterodimer_GO) <- c('Term', 'Function',
                            'Percent', 'Fold',
                            'Bonferroni','Benjamini')
heterodimer_GO[, 'Benjamini'] <- (-log(heterodimer_GO$Benjamini))
heterodimer_GO[, 'Bonferroni'] <- (-log(heterodimer_GO$Bonferroni))

# combine the term
homohetero_GO <- merge(homodimer_GO, heterodimer_GO, by.x='Term', by.y='Term')
homohetero_GO <- subset(homohetero_GO, select=-Function.y)
colnames(homohetero_GO) <- c('Term', 'Function',
                             'Percent.Homo', 'Fold.Homo',
                             'Bonferroni.Homo','Benjamini.Homo',
                             'Percent.Hetero', 'Fold.Hetero',
                             'Bonferroni.Hetero','Benjamini.Hetero')

head(homohetero_GO)    

# Benjamini 
Barplot_Chunk(dataTable=homohetero_GO, N=12,
              vars=c('Function', 'Benjamini.Homo', 'Benjamini.Hetero'), 
              ylabel='- Log(P Value)',
              output_n= 'figs/homohetero_BenjaminiGO', TERM=FALSE)

# Percent
Barplot_Chunk(dataTable=homohetero_GO, N=12,
              vars=c('Function', 'Percent.Homo', 'Percent.Hetero'), 
              ylabel='Percent',
              output_n= 'figs/homohetero_PercentGO', TERM=FALSE)



homodimerOnly_GO <- subset(homodimer_GO, !homodimer_GO$Term %in% heterodimer_GO$Term)
heterodimerOnly_GO <- subset(heterodimer_GO, !heterodimer_GO$Term %in% homodimer_GO$Term)
rownames(heterodimerOnly_GO) <- 1:nrow(heterodimerOnly_GO)
rownames(homodimerOnly_GO) <- 1:nrow(homodimerOnly_GO)
homodimerOnly_GO$Function <- substr(homodimerOnly_GO$Function, 1, 50) 
head(homodimerOnly_GO)
dim(heterodimerOnly_GO)


# homodimerOnly Benjamini
Barplot_Chunk(dataTable=homodimerOnly_GO, N=20,
              vars=c('Function', 'Benjamini'), 
              ylabel='- Log(P Value)',
              output_n='figs/homodimerOnly_BenjaminiGO', TERM=FALSE)

# homodimerOnly Percent
Barplot_Chunk(dataTable=homodimerOnly_GO, N=20,
              vars=c('Function', 'Percent'), 
              ylabel='Percent',
              output_n='figs/homodimerOnly_PercentGO', TERM=FALSE)

# heterodimerOnly Benjamini 
Barplot_Chunk(dataTable=heterodimerOnly_GO, N=20,
              vars=c('Function', 'Benjamini'), 
              ylabel='- Log(P Value)',
              output_n='figs/heteroOnly_BenjaminiGO', TERM=FALSE)

# heterodimerOnly Percent
Barplot_Chunk(dataTable=heterodimerOnly_GO, N=20,
              vars=c('Function', 'Percent'), 
              ylabel='Percent',
              output_n='figs/heteroOnly_PercentGO', TERM=FALSE)


annot_GO_homohetero <- subset(homohetero_GO, select=c('Term', 'Function'))
annot_GO_homohetero_chunks <-  split(annot_GO_homohetero,
                    (as.numeric(rownames(annot_GO_homohetero))-1) %/% 35 )        
length(annot_GO_homohetero_chunks)

annot_GO_homo <- subset(homodimerOnly_GO, select=c('Term', 'Function'))
annot_GO_homo_chunks <-  split(annot_GO_homo,
                    (as.numeric(rownames(annot_GO_homo))-1) %/% 35 )        
length(annot_GO_homo_chunks)

annot_GO_hetero <- subset(heterodimerOnly_GO, select=c('Term', 'Function'))
annot_GO_hetero_chunks <-  split(annot_GO_hetero,
                    (as.numeric(rownames(annot_GO_hetero))-1) %/% 35 )        
length(annot_GO_hetero_chunks)

@


\clearpage
\subsection{GO Annotation in HomoHeterodimer}
<<GOannotHomoHetero1, echo=FALSE, results='asis'>>=
print(xtable(annot_GO_homohetero_chunks[[1]], caption='GO Functional Annotation in Homo and Heterodimer (1)'))
@
\clearpage
<<GOannotHomoHetero2, echo=FALSE, results='asis'>>=
print(xtable(annot_GO_homohetero_chunks[[2]], caption='GO Functional Annotation in Homo and Heterodimer (2)'))
@
\clearpage

\subsection{GO Annotation in Homodimer}
<<GOannotHomo1, echo=FALSE, results='asis'>>=
print(xtable(annot_GO_homo_chunks[[1]], caption='GO Functional Annotation in Homodimer (1)'))
@
\clearpage
<<GOannotHomo2, echo=FALSE, results='asis'>>=
print(xtable(annot_GO_homo_chunks[[2]], caption='GO Functional Annotation in Homodimer (2)'))
@
\clearpage
<<GOannotHomo3, echo=FALSE, results='asis'>>=
print(xtable(annot_GO_homo_chunks[[3]], caption='GO Functional Annotation in Homodimer (3)'))
@
\clearpage
<<GOannotHomo4, echo=FALSE, results='asis'>>=
print(xtable(annot_GO_homo_chunks[[4]], caption='GO Functional Annotation in Homodimer (4)'))
@
\clearpage
<<GOannotHomo5, echo=FALSE, results='asis'>>=
print(xtable(annot_GO_homo_chunks[[5]], caption='GO Functional Annotation in Homodimer (5)'))
@
\clearpage
<<GOannotHomo6, echo=FALSE, results='asis'>>=
print(xtable(annot_GO_homo_chunks[[6]], caption='GO Functional Annotation in Homodimer (6)'))
@
\clearpage
<<GOannotHomo7, echo=FALSE, results='asis'>>=
print(xtable(annot_GO_homo_chunks[[7]], caption='GO Functional Annotation in Homodimer (7)'))
@
\clearpage
<<GOannotHomo8, echo=FALSE, results='asis'>>=
print(xtable(annot_GO_homo_chunks[[8]], caption='GO Functional Annotation in Homodimer (8)'))
@
\clearpage
<<GOannotHomo9, echo=FALSE, results='asis'>>=
print(xtable(annot_GO_homo_chunks[[9]], caption='GO Functional Annotation in Homodimer (9)'))
@
\clearpage
<<GOannotHomo10, echo=FALSE, results='asis'>>=
print(xtable(annot_GO_homo_chunks[[10]], caption='GO Functional Annotation in Homodimer (10)'))
@
\clearpage

\subsection{GO Annotation in Heterodimer}
<<GOannotHetero1, echo=FALSE, results='asis'>>=
print(xtable(annot_GO_hetero_chunks[[1]], caption='GO Functional Annotation in Heterodimer (1)'))
@
\clearpage
<<GOannotHetero2, echo=FALSE, results='asis'>>=
print(xtable(annot_GO_hetero_chunks[[2]], caption='GO Functional Annotation in Heterodimer (2)'))
@
\clearpage
<<GOannotHetero3, echo=FALSE, results='asis'>>=
print(xtable(annot_GO_hetero_chunks[[3]], caption='GO Functional Annotation in Heterodimer (3)'))
@
\clearpage

\subsection{Benjamini P-Value of David GO-Terms in Homo vs Heterodimer}
\begin{figure}[!htp]
    \centering
    \subfloat{\includegraphics[width=5.5in, height=2in]{figs/homohetero_BenjaminiGO_1.pdf}}
    \\
    \subfloat{\includegraphics[width=5.5in, height=2in]{figs/homohetero_BenjaminiGO_2.pdf}}
    \\
    \subfloat{\includegraphics[width=5.5in, height=2in]{figs/homohetero_BenjaminiGO_3.pdf}}
    \\
    \subfloat{\includegraphics[width=5.5in, height=2in]{figs/homohetero_BenjaminiGO_4.pdf}}
    \caption{Benjamini P-Value in Homo and Heterodimer ($-log(p value)$)}
    \label{fig:benjaminiGO}
\end{figure}
\clearpage

\subsection{Percent of David GO-Terms in Homo vs Heterodimer}
\begin{figure}[!htp]
    \centering
    \subfloat{\includegraphics[width=5.5in, height=2in]{figs/homohetero_PercentGO_1.pdf}}
    \\
    \subfloat{\includegraphics[width=5.5in, height=2in]{figs/homohetero_PercentGO_2.pdf}}
    \\
    \subfloat{\includegraphics[width=5.5in, height=2in]{figs/homohetero_PercentGO_3.pdf}}
    \\
    \subfloat{\includegraphics[width=5.5in, height=2in]{figs/homohetero_PercentGO_4.pdf}}
    \caption{Percent GO-Term in Homo and Heterodimer}
    \label{fig:benjaminiGO}
\end{figure}
\clearpage

\subsection{Benjamini P-Value of David GO-Terms in Homodimer Only}
\begin{figure}[!htp]
    \centering
    \subfloat{\includegraphics[width=5.5in, height=2in]{figs/homodimerOnly_BenjaminiGO_1.pdf}}
    \\
    \subfloat{\includegraphics[width=5.5in, height=2in]{figs/homodimerOnly_BenjaminiGO_2.pdf}}
    \\
    \subfloat{\includegraphics[width=5.5in, height=2in]{figs/homodimerOnly_BenjaminiGO_3.pdf}}
    \\
    \subfloat{\includegraphics[width=5.5in, height=2in]{figs/homodimerOnly_BenjaminiGO_4.pdf}}
\end{figure}
\clearpage

\begin{figure}[!htp]
    \centering
    \subfloat{\includegraphics[width=5.5in, height=2in]{figs/homodimerOnly_BenjaminiGO_5.pdf}}
    \\
    \subfloat{\includegraphics[width=5.5in, height=2in]{figs/homodimerOnly_BenjaminiGO_6.pdf}}
    \\
    \subfloat{\includegraphics[width=5.5in, height=2in]{figs/homodimerOnly_BenjaminiGO_7.pdf}}
    \\
    \subfloat{\includegraphics[width=5.5in, height=2in]{figs/homodimerOnly_BenjaminiGO_8.pdf}}
\end{figure}
\clearpage

\begin{figure}[!htp]
    \centering
    \subfloat{\includegraphics[width=5.5in, height=2in]{figs/homodimerOnly_BenjaminiGO_9.pdf}}
    \\
    \subfloat{\includegraphics[width=5.5in, height=2in]{figs/homodimerOnly_BenjaminiGO_10.pdf}}
    \\
    \subfloat{\includegraphics[width=5.5in, height=2in]{figs/homodimerOnly_BenjaminiGO_11.pdf}}
    \\
    \subfloat{\includegraphics[width=5.5in, height=2in]{figs/homodimerOnly_BenjaminiGO_12.pdf}}
\end{figure}
\clearpage

\begin{figure}[!htp]
    \centering
    \subfloat{\includegraphics[width=5.5in, height=2in]{figs/homodimerOnly_BenjaminiGO_13.pdf}}
    \\
    \subfloat{\includegraphics[width=5.5in, height=2in]{figs/homodimerOnly_BenjaminiGO_14.pdf}}
    \\
    \subfloat{\includegraphics[width=5.5in, height=2in]{figs/homodimerOnly_BenjaminiGO_15.pdf}}
\end{figure}
\clearpage

\begin{figure}[!htp]
    \centering
    \subfloat{\includegraphics[width=5.5in, height=2in]{figs/homodimerOnly_BenjaminiGO_16.pdf}}
    \\
    \subfloat{\includegraphics[width=5.5in, height=2in]{figs/homodimerOnly_BenjaminiGO_17.pdf}}
    \\
    \subfloat{\includegraphics[width=5.5in, height=2in]{figs/homodimerOnly_BenjaminiGO_18.pdf}}
    \caption{Benjamini P-Value in Homodimer Only ($-log(p value)$)}
    \label{fig:benjaminiHomoOnlyGO}
\end{figure}
\clearpage

\subsection{Percent of David GO-Terms in Homodimer Only}
\begin{figure}[!htp]
    \centering
    \subfloat{\includegraphics[width=5.5in, height=2in]{figs/homodimerOnly_PercentGO_1.pdf}}
    \\
    \subfloat{\includegraphics[width=5.5in, height=2in]{figs/homodimerOnly_PercentGO_2.pdf}}
    \\
    \subfloat{\includegraphics[width=5.5in, height=2in]{figs/homodimerOnly_PercentGO_3.pdf}}
    \\
    \subfloat{\includegraphics[width=5.5in, height=2in]{figs/homodimerOnly_PercentGO_4.pdf}}
\end{figure}
\clearpage

\begin{figure}[!htp]
    \centering
    \subfloat{\includegraphics[width=5.5in, height=2in]{figs/homodimerOnly_PercentGO_4.pdf}}
    \\
    \subfloat{\includegraphics[width=5.5in, height=2in]{figs/homodimerOnly_PercentGO_5.pdf}}
    \\
    \subfloat{\includegraphics[width=5.5in, height=2in]{figs/homodimerOnly_PercentGO_6.pdf}}
    \\
    \subfloat{\includegraphics[width=5.5in, height=2in]{figs/homodimerOnly_PercentGO_7.pdf}}
\end{figure}
\clearpage

\begin{figure}[!htp]
    \centering
    \subfloat{\includegraphics[width=5.5in, height=2in]{figs/homodimerOnly_PercentGO_8.pdf}}
    \\
    \subfloat{\includegraphics[width=5.5in, height=2in]{figs/homodimerOnly_PercentGO_9.pdf}}
    \\
    \subfloat{\includegraphics[width=5.5in, height=2in]{figs/homodimerOnly_PercentGO_10.pdf}}
    \\
    \subfloat{\includegraphics[width=5.5in, height=2in]{figs/homodimerOnly_PercentGO_11.pdf}}
\end{figure}
\clearpage

\begin{figure}[!htp]
    \centering
    \subfloat{\includegraphics[width=5.5in, height=2in]{figs/homodimerOnly_PercentGO_12.pdf}}
    \\
    \subfloat{\includegraphics[width=5.5in, height=2in]{figs/homodimerOnly_PercentGO_13.pdf}}
    \\
    \subfloat{\includegraphics[width=5.5in, height=2in]{figs/homodimerOnly_PercentGO_14.pdf}}
\end{figure}
\clearpage

\begin{figure}[!htp]
    \centering
    \subfloat{\includegraphics[width=5.5in, height=2in]{figs/homodimerOnly_PercentGO_15.pdf}}
    \\
    \subfloat{\includegraphics[width=5.5in, height=2in]{figs/homodimerOnly_PercentGO_16.pdf}}
    \\
    \subfloat{\includegraphics[width=5.5in, height=2in]{figs/homodimerOnly_PercentGO_17.pdf}}
    \\
    \subfloat{\includegraphics[width=5.5in, height=2in]{figs/homodimerOnly_PercentGO_18.pdf}}
    \caption{Percent in Homodimer Only}
    \label{fig:percentHomoOnlyGO}
\end{figure}
\clearpage

\subsection{Benjamini P-Value of David GO-Terms in Heterodimer Only}
\begin{figure}[!htp]
    \centering
    \subfloat{\includegraphics[width=5.5in, height=2in]{figs/heteroOnly_BenjaminiGO_1.pdf}}
    \\
    \subfloat{\includegraphics[width=5.5in, height=2in]{figs/heteroOnly_BenjaminiGO_2.pdf}}
    \\
    \subfloat{\includegraphics[width=5.5in, height=2in]{figs/heteroOnly_BenjaminiGO_3.pdf}}
    \\
    \subfloat{\includegraphics[width=5.5in, height=2in]{figs/heteroOnly_BenjaminiGO_4.pdf}}
    \caption{Benjamini P-Value in Heterodimer Only ($-log(p value)$)}
    \label{fig:benjaminiHeteroOnlyGO}
\end{figure}
\clearpage

\subsection{Percent of David GO-Terms in Heterodimer Only}
\begin{figure}[!htp]
    \centering
    \subfloat{\includegraphics[width=5.5in, height=2in]{figs/heteroOnly_PercentGO_1.pdf}}
    \\
    \subfloat{\includegraphics[width=5.5in, height=2in]{figs/heteroOnly_PercentGO_2.pdf}}
    \\
    \subfloat{\includegraphics[width=5.5in, height=2in]{figs/heteroOnly_PercentGO_3.pdf}}
    \\
    \subfloat{\includegraphics[width=5.5in, height=2in]{figs/heteroOnly_PercentGO_4.pdf}}
    \caption{Percent in Heterodimer Only}
    \label{fig:benjaminiHeteroOnlyGO}
\end{figure}
\clearpage


\section{Pathway}
<<GOPathway, cache=TRUE>>=
homodimer_path <- read.table(paste0(work_dir,
                    'CebpE/Output/ChipMeme/Motif/',
                    'homo_Pathway_Percent_Fold_Bonferroni_Benjamini.txt'),
                    header=FALSE,sep='\t')

colnames(homodimer_path) <- c('Term', 'Function',
                            'Percent', 'Fold',
                            'Bonferroni','Benjamini')
homodimer_path[, 'Benjamini'] <- (-log(homodimer_path$Benjamini))
homodimer_path[, 'Bonferroni'] <- (-log(homodimer_path$Bonferroni))
head(homodimer_path)

heterodimer_path <- read.table(paste0(work_dir,
                    'CebpE/Output/ChipMeme/Motif/',
                    'hetero_Pathway_Percent_Fold_Bonferroni_Benjamini.txt'),
                    header=FALSE,sep='\t')
colnames(heterodimer_path) <- c('Term', 'Function',
                            'Percent', 'Fold',
                            'Bonferroni','Benjamini')
heterodimer_path[, 'Benjamini'] <- (-log(heterodimer_path$Benjamini))
heterodimer_path[, 'Bonferroni'] <- (-log(heterodimer_path$Bonferroni))

# combine the term
homohetero_path <- merge(homodimer_path, heterodimer_path, by.x='Term', by.y='Term')
homohetero_path <- subset(homohetero_path, select=-Function.y)
head(homohetero_path)
colnames(homohetero_path) <- c('Term', 'Function',
                             'Percent.Homo', 'Fold.Homo',
                             'Bonferroni.Homo','Benjamini.Homo',
                             'Percent.Hetero', 'Fold.Hetero',
                             'Bonferroni.Hetero','Benjamini.Hetero')
dim(homohetero_path)
head(homohetero_path)
# Benjamini 
Barplot_Chunk(dataTable=homohetero_path, N=2,
              vars=c('Function', 'Benjamini.Homo', 'Benjamini.Hetero'), 
              ylabel='- Log(P Value)',
              output_n='figs/homohetero_BenjaminiPath', TERM=FALSE)
# Percent
Barplot_Chunk(dataTable=homohetero_path, N=2,
              vars=c('Function', 'Percent.Homo', 'Percent.Hetero'), 
              ylabel='Percent',
              output_n='figs/homohetero_PercentPath', TERM=FALSE)

# homodimerOnly or heterodimerOnly
homodimerOnly_path <- subset(homodimer_path, !homodimer_path$Term %in% heterodimer_path$Term)
heterodimerOnly_path <- subset(heterodimer_path, !heterodimer_path$Term %in% homodimer_path$Term)
rownames(heterodimerOnly_path) <- 1:nrow(heterodimerOnly_path)
rownames(homodimerOnly_path) <- 1:nrow(homodimerOnly_path)

# homodimerOnly Benjamini
Barplot_Chunk(dataTable=homodimerOnly_path, N=20,
              vars=c('Function', 'Benjamini'), 
              ylabel='- Log(P Value)',
              output_n='figs/homodimerOnly_BenjaminiPath', TERM=FALSE)

# homodimerOnly Percent
Barplot_Chunk(dataTable=homodimerOnly_path, N=20,
              vars=c('Function', 'Percent'), 
              ylabel='Percent',
              output_n='figs/homodimerOnly_PercentPath', TERM=FALSE)

# heterodimerOnly Benjamini 
Barplot_Chunk(dataTable=heterodimerOnly_path, N=7,
              vars=c('Function', 'Benjamini'), 
              ylabel='- Log(P Value)',
              output_n='figs/heteroOnly_BenjaminiPath', TERM=FALSE)

# heterodimerOnly Percent
Barplot_Chunk(dataTable=heterodimerOnly_path, N=7,
              vars=c('Function', 'Percent'), 
              ylabel='Percent',
              output_n='figs/heteroOnly_PercentPath', TERM=FALSE)

annot_Path <- subset(homohetero_path, select=c('Term', 'Function'))
annot_Path_homoOnly <- subset(homodimerOnly_path, select=c('Term', 'Function'))
annot_Path_heteroOnly <- subset(heterodimerOnly_path, select=c('Term', 'Function'))
@

\clearpage
\subsection{Pathway GO Annotation Homo-Heterodimer}
<<PathwayAnnotHomoHetero, echo=FALSE, results='asis'>>=
print(xtable(annot_Path, caption='GO Pathway Annotation (Homo-Heterodimer)'))
@
\subsection{Pathway GO Annotation Heterodimer}
<<PathwayAnnotHeteroOnly, echo=FALSE, results='asis'>>=
print(xtable(annot_Path_heteroOnly, caption='GO Pathway Annotation (Heterodimer Only)'))
@
\clearpage

\subsection{Pathway GO Annotation Homodimer}
<<PathwayAnnotHomoOnly, echo=FALSE, results='asis'>>=
print(xtable(annot_Path_homoOnly, caption='GO Pathway Annotation (Homodimer Only)'))
@
\clearpage


\clearpage
\subsection{Benjamini P-Value of David GO-Pathway in Homo vs Heterodimer}
\begin{figure}[!htp]
    \centering
    \subfloat{\includegraphics[width=5.5in, height=2in]{figs/homohetero_BenjaminiPath_1.pdf}}
    \caption{Benjamini P-Value in Homo and Heterodimer ($-log(p value)$)}
    \label{fig:benjaminiPath}
\end{figure}
\clearpage

\subsection{Percent of David GO-Pathway in Homo vs Heterodimer}
\begin{figure}[!htp]
    \centering
    \subfloat{\includegraphics[width=5.5in, height=2in]{figs/homohetero_PercentPath_1.pdf}}
    \caption{Percent of David-GO Pathway in Homo and Heterodimer}
    \label{fig:percentPath}
\end{figure}
\clearpage

\subsection{Benjamini P-Value of David GO-Pathway in Homodimer Only}
\begin{figure}[!htp]
    \centering
    \subfloat{\includegraphics[width=5.5in, height=3in]{figs/homodimerOnly_BenjaminiPath_1.pdf}}
    \\
    \subfloat{\includegraphics[width=5.5in, height=3in]{figs/homodimerOnly_BenjaminiPath_2.pdf}}
    \caption{Benjamini P-Value in Homodimer Only ($-log(p value)$)}
    \label{fig:BenjaminiPathHomodimer}
\end{figure}
\clearpage

\subsection{Percent of David GO-Pathway in Homodimer Only}
\begin{figure}[!htp]
    \centering
    \subfloat{\includegraphics[width=5.5in, height=3in]{figs/homodimerOnly_PercentPath_1.pdf}}
    \\
    \subfloat{\includegraphics[width=5.5in, height=3in]{figs/homodimerOnly_PercentPath_2.pdf}}
    \caption{Percent of David GO-Pathway in Homodimer Only}
    \label{fig:PercentPathHomodimer}
\end{figure}
\clearpage


\subsection{Benjamini P-Value of David GO-Pathway in Heterodimer Only}
\begin{figure}[!htp]
    \centering
    \subfloat{\includegraphics[width=5.5in, height=2in]{figs/heteroOnly_BenjaminiPath_1.pdf}}
    \caption{Benjamini P-Value in Heterodimer Only ($-log(p value)$)}
    \label{fig:BenjaminiPathHeterodimer}
\end{figure}
\clearpage

\subsection{Percent of David GO-Pathway in Heterodimer Only}
\begin{figure}[!htp]
    \centering
    \subfloat{\includegraphics[width=5.5in, height=2in]{figs/heteroOnly_PercentPath_1.pdf}}
    \caption{Percent in Heterodimer Only}
    \label{fig:PercentPathHeterodimer}
\end{figure}
\clearpage


\section{Protein Interaction: DavidGo}
<<InteractDavid, cache=TRUE>>=
homodimer_Interact <- read.table(paste0(work_dir,
                    'CebpE/Output/ChipMeme/Motif/',
                    'homo_InteractChart_Percent_Fold_Bonferroni_Benjamini.txt'),
                    header=FALSE,sep='\t')

colnames(homodimer_Interact) <- c('Term', 'Percent', 'Fold', 'Bonferroni','Benjamini')
homodimer_Interact[, 'Bonferroni'] <- (-log(homodimer_Interact$Bonferroni))
homodimer_Interact[, 'Benjamini'] <- (-log(homodimer_Interact$Benjamini))
head(homodimer_Interact)

heterodimer_Interact <- read.table(paste0(work_dir,
                    'CebpE/Output/ChipMeme/Motif/',
                    'hetero_InteractChart_Percent_Fold_Bonferroni_Benjamini.txt'),
                    header=FALSE,sep='\t')
colnames(heterodimer_Interact) <- c('Term', 'Percent', 'Fold', 'Bonferroni','Benjamini')
heterodimer_Interact[, 'Bonferroni'] <- (-log(heterodimer_Interact$Bonferroni))
heterodimer_Interact[, 'Benjamini'] <- (-log(heterodimer_Interact$Benjamini))

# combine the term
homohetero_Interact <- merge(homodimer_Interact, heterodimer_Interact, by.x='Term', by.y='Term')
colnames(homohetero_Interact) <- c('Term', 
                             'Percent.Homo','Fold.Homo', 'Bonferroni.Homo','Benjamini.Homo',
                             'Percent.Hetero','Fold.Hetero', 'Bonferroni.Hetero','Benjamini.Hetero')

head(homohetero_Interact)    
dim(homohetero_Interact)

# Benjamini 
Barplot_Chunk(dataTable=homohetero_Interact, N=12,
              vars=c('Term', 'Benjamini.Homo', 'Benjamini.Hetero'), 
              ylabel='- Log(P Value)',
              output_n= 'figs/homohetero_BenjaminiInteract', TERM=TRUE)

# Percent
Barplot_Chunk(dataTable=homohetero_Interact, N=12,
              vars=c('Term', 'Percent.Homo', 'Percent.Hetero'), 
              ylabel='Percent',
              output_n= 'figs/homohetero_PercentInteract', TERM=TRUE)



homodimerOnly_Interact <- subset(homodimer_Interact, !homodimer_Interact$Term %in% heterodimer_Interact$Term)
heterodimerOnly_Interact <- subset(heterodimer_Interact, !heterodimer_Interact$Term %in% homodimer_Interact$Term)
rownames(heterodimerOnly_Interact) <- 1:nrow(heterodimerOnly_Interact)
rownames(homodimerOnly_Interact) <- 1:nrow(homodimerOnly_Interact)
head(homodimerOnly_Interact)


# homodimerOnly Benjamini
Barplot_Chunk(dataTable=homodimerOnly_Interact, N=21,
              vars=c('Term', 'Benjamini'), 
              ylabel='- Log(P Value)',
              output_n='figs/homodimerOnly_BenjaminiInteract', TERM=TRUE)

# homodimerOnly Percent
Barplot_Chunk(dataTable=homodimerOnly_Interact, N=21,
              vars=c('Term', 'Percent'), 
              ylabel='Percent',
              output_n='figs/homodimerOnly_PercentInteract', TERM=TRUE)

# heterodimerOnly Benjamini 
Barplot_Chunk(dataTable=heterodimerOnly_Interact, N=20,
              vars=c('Term', 'Benjamini'), 
              ylabel='- Log(P Value)',
              output_n='figs/heteroOnly_BenjaminiInteract', TERM=TRUE)

# heterodimerOnly Percent
Barplot_Chunk(dataTable=heterodimerOnly_Interact, N=20,
              vars=c('Term', 'Percent'), 
              ylabel='Percent',
              output_n='figs/heteroOnly_PercentInteract', TERM=TRUE)



@
\clearpage

\subsection{Benjamini P-Value of David Interaction-Terms in Homo vs Heterodimer}
\begin{figure}[!htp]
    \centering
    \subfloat{\includegraphics[width=5.5in, height=2in]{figs/homohetero_BenjaminiInteract_1.pdf}}
    \\
    \subfloat{\includegraphics[width=5.5in, height=2in]{figs/homohetero_BenjaminiInteract_2.pdf}}
    \\
    \subfloat{\includegraphics[width=5.5in, height=2in]{figs/homohetero_BenjaminiInteract_3.pdf}}
    \\
    \subfloat{\includegraphics[width=5.5in, height=2in]{figs/homohetero_BenjaminiInteract_4.pdf}}
\end{figure}
\clearpage

\begin{figure}[!htp]
    \centering
    \subfloat{\includegraphics[width=5.5in, height=2in]{figs/homohetero_BenjaminiInteract_5.pdf}}
    \\
    \subfloat{\includegraphics[width=5.5in, height=2in]{figs/homohetero_BenjaminiInteract_6.pdf}}
    \\
    \subfloat{\includegraphics[width=5.5in, height=2in]{figs/homohetero_BenjaminiInteract_7.pdf}}
    \\
    \subfloat{\includegraphics[width=5.5in, height=2in]{figs/homohetero_BenjaminiInteract_8.pdf}}
    \caption{Benjamini P-Value in Homo and Heterodimer ($-log(p value)$) Interaction}
    \label{fig:benjaminiInteraction}
\end{figure}
\clearpage

\subsection{Percent of David Interaction-Terms in Homo vs Heterodimer}
\begin{figure}[!htp]
    \centering
    \subfloat{\includegraphics[width=5.5in, height=2in]{figs/homohetero_PercentInteract_1.pdf}}
    \\
    \subfloat{\includegraphics[width=5.5in, height=2in]{figs/homohetero_PercentInteract_2.pdf}}
    \\
    \subfloat{\includegraphics[width=5.5in, height=2in]{figs/homohetero_PercentInteract_3.pdf}}
    \\
    \subfloat{\includegraphics[width=5.5in, height=2in]{figs/homohetero_PercentInteract_4.pdf}}
\end{figure}
\clearpage

\begin{figure}[!htp]
    \centering
    \subfloat{\includegraphics[width=5.5in, height=2in]{figs/homohetero_PercentInteract_5.pdf}}
    \\
    \subfloat{\includegraphics[width=5.5in, height=2in]{figs/homohetero_PercentInteract_6.pdf}}
    \\
    \subfloat{\includegraphics[width=5.5in, height=2in]{figs/homohetero_PercentInteract_7.pdf}}
    \\
    \subfloat{\includegraphics[width=5.5in, height=2in]{figs/homohetero_PercentInteract_8.pdf}}
    \caption{Percent in Homo and Heterodimer ($-log(p value)$) Interaction}
    \label{fig:benjaminiInteraction}
\end{figure}
\clearpage

\subsection{Benjamini P-Value of David GO-Terms in Homodimer Only}
\begin{figure}[!htp]
    \centering
    \subfloat{\includegraphics[width=5.5in, height=2in]{figs/homodimerOnly_BenjaminiInteract_1.pdf}}
    \\
    \subfloat{\includegraphics[width=5.5in, height=2in]{figs/homodimerOnly_BenjaminiInteract_2.pdf}}
    \caption{Benjamini P-Value in Homodimer Only ($-log(p value)$)}
    \label{fig:benjaminiHomodimerOnly}
\end{figure}
\clearpage

\subsection{Percent of David GO-Terms in Homodimer Only}
\begin{figure}[!htp]
    \centering
    \subfloat{\includegraphics[width=5.5in, height=2in]{figs/homodimerOnly_PercentInteract_1.pdf}}
    \\
    \subfloat{\includegraphics[width=5.5in, height=2in]{figs/homodimerOnly_PercentInteract_2.pdf}}
    \caption{Percent of David GO in Homodimer Only}
    \label{fig:percentHomodimerOnly}
\end{figure}
\clearpage

\subsection{Benjamini P-Value of David GO-Terms in Heterodimer Only}
\begin{figure}[!htp]
    \centering
    \subfloat{\includegraphics[width=5.5in, height=2in]{figs/heteroOnly_BenjaminiInteract_1.pdf}}
    \caption{Benjamini P-Value in Heterodimer Only ($-log(p value)$)}
    \label{fig:benjaminiHeterodimerOnly}
\end{figure}
\clearpage

\subsection{Percent of David GO-Terms in Heterodimer Only}
\begin{figure}[!htp]
    \centering
    \subfloat{\includegraphics[width=5.5in, height=2in]{figs/heteroOnly_PercentInteract_1.pdf}}
    \caption{Percent of David GO in Heterodimer Only}
    \label{fig:percentHeterodimerOnly}
\end{figure}
\clearpage


\begin{verbatim}

  Filename: dimerAnalysis.Rnw
  Working directory: \Sexpr{getwd()}
\end{verbatim}

\section{Metainfo}
<<>>=
sessionInfo()
@

<<knitIt, cache=TRUE, results='hide', message=FALSE, warning=FALSE>>=
library(knitr)
purl("dimerAnalysis.Rnw" ) # compile to tex
purl("dimerAnalysis.Rnw", documentation = 0) # extract R code only
knit2pdf("dimerAnalysis.Rnw")
@

\end{document}

