
## ----setup, include=FALSE, cache=TRUE------------------------------------
# set global chunk options
# for figures
opts_chunk$set(fig.path='figs/', fig.align='center', fig.show='hold',
               dev='CairoPDF', out.width='.4\\linewidth')
# replacing "=" into "->" to make it R thing
options(replace.assign=TRUE,width=90)
# caching chunks
opts_chunk$set(cache.extra = R.version,cache.path='cache/')
opts_chunk$set(cache.extra = rand_seed)


## ----Rcodes--------------------------------------------------------------
source('/home/ricky/Rlim/ChromatinConformation/ComponentCalls/ComponentCalls.R')
work_dir = '/home/ricky/Rlim/ChromatinConformation/ComponentCalls/CebpE/'


## ----Dataset, cache=TRUE-------------------------------------------------
Koeffler_BM_CebpE <- read.table(paste0(work_dir, 
                        'Input/KoefflerLab_BM_ChIPseq_CebpE_mm10_q10rmdup_peaks.xls'), 
                        header=T, sep='\t', row.names=10, skip=28)
head(Koeffler_BM_CebpE)
log_pileup <- log10(Koeffler_BM_CebpE$pileup)
Koeffler_BM_CebpE_log <- Koeffler_BM_CebpE
head(Koeffler_BM_CebpE_log)
Koeffler_BM_CebpE_log[, 'pileup'] <- log_pileup

p1 <- ggplot(Koeffler_BM_CebpE, aes(x=pileup)) +
        geom_histogram(aes(y = ..density..), fill='#969696', binwidth=25) +
        geom_line(stat='density', alpha=0.5, size=1.5) +
        scale_x_continuous(breaks=seq(0,450, 25)) + 
        ggtitle('Distribution of ChIP-seq Peaks (Koeffler_BM_CebpE)')+
        xlab('Score')
ggsave('figs/Koeffler_BM_CebpE_CountChipSeqPeaks.pdf', p1)

#summary(Koeffler_BM_CebpE$pileup)
#summary(log10(Koeffler_BM_CebpE$pileup))
p2 <- ggplot(Koeffler_BM_CebpE, aes(x=pileup)) +
        geom_histogram(aes(y = ..density..), fill='#969696', binwidth=.05) +
        geom_line(stat='density', alpha=0.5, size=1.5) +
        scale_x_log10(breaks=seq(25,450, 50)) + 
        ggtitle('Distribution of Log-Transformed ChIP-seq Peaks (Koeffler_BM_CebpE)') +
        xlab('Score')
ggsave('figs/Koeffler_BM_CebpE_CountChipSeqPeaks_log.pdf', p2)

#grid.arrange(p1, p2, ncol=2)
#p <- arrangeGrob(p1,p2, ncol=2)
#ggsave('figs/Koeffler_BM_CebpE_CountChipSeqPeaks.pdf', p)




## ----ModelFits, cache=TRUE-----------------------------------------------
library(MASS)

set.seed(123)
chip_data <- sort(sample(Koeffler_BM_CebpE$pileup, 1000))
n <- length(chip_data)

# fitting with models
normal.par <- fitdistr(chip_data, 'normal')
poisson.par <- fitdistr(chip_data, 'Poisson')
negbi.par <- fitdistr(chip_data, 'negative binomial')

# counts estimates generated by models
normal.estimate <- rnorm(n, normal.par$estimate)
poisson.estimate <- rpois(n, poisson.par$estimate)
negbi.estimate <- rnbinom(n, size=negbi.par$estimate['size'], mu=negbi.par$estimate['mu'])


## ----PlotModelFits, echo=FALSE-------------------------------------------
pdf('figs/Koeffler_BM_CebpE_normalModel.pdf', 
    useDingbats=FALSE)
plot(chip_data, sort(normal.estimate),
     xlim = range(1:100), ylim = range(1:100), pch = 20,
     xlab = 'Emperical ChIPseq PileUp', 
     ylab = 'Model Estimates', 
     main = 'ChIPseq Counts Modeled with Normal', bty='n')
abline(0,1, col='red')
legend('topright', paste('loglik: ', round(normal.par$loglik, 2)), bty='n')
dev.off()

pdf('figs/Koeffler_BM_CebpE_poissonModel.pdf', 
    useDingbats=FALSE)
plot(chip_data, sort(poisson.estimate),
     xlim = range(1:100), ylim = range(1:100), pch = 20,
     xlab = 'Emperical ChIPseq PileUp', 
     ylab = 'Model Estimates', 
     main = 'ChIPseq Counts Modeled with Poisson', bty='n')
abline(0,1, col='red')
legend('topright', paste('loglik: ', round(poisson.par$loglik, 2)), bty='n')
dev.off()


pdf('figs/Koeffler_BM_CebpE_negBinomModel.pdf', 
    useDingbats=FALSE)
plot(chip_data, sort(negbi.estimate),
     xlim = range(1:100), ylim = range(1:100), pch = 20,
     xlab = 'Emperical ChIPseq PileUp', 
     ylab = 'Model Estimates', 
     main = 'ChIPseq Counts Modeled with Neg.Binomial', bty='n')
abline(0,1, col='red')
legend('topright', paste('loglik: ', round(negbi.par$loglik, 2)), bty='n')
dev.off()


## ----FitGMMS, results='hide', cache=TRUE---------------------------------

# fit with several k-component-GMMs
GMMs_list_Koeffler_BM_CebpE <- fitMMs(X=Koeffler_BM_CebpE$pileup, max_k=10, model = 'GMM')



## ----FitGMMs_log, results='hide', cache=TRUE-----------------------------
GMMs_list_Koeffler_BM_CebpE_log <- fitMMs(X=Koeffler_BM_CebpE_log$pileup, max_k=10, model = 'GMM')


## ----fitNB, results='hide', cache=TRUE-----------------------------------
NBMs_list_Koeffler_BM_CebpE <- fitMMs(X=Koeffler_BM_CebpE$pileup, max_k=10, 'NBM')


## ----ModelParameterGMM, echo=FALSE, cache=TRUE---------------------------

#invisible(lapply(GMMs_list_Koeffler_BM_CebpE, function(x)tidy(summary(x))))



## ----VisualizeFitGMMs, results='hide', message=FALSE, cache=TRUE---------

visualizeFitMMs(X=Koeffler_BM_CebpE, MMs_list=GMMs_list_Koeffler_BM_CebpE, 
                max_k=10, output_n='figs/Koeffler_BM_CebpE_GMM_ModelVisualization', 
                model = 'GMM', titleName='Koeffler_BM_CebpE') 



## ----VisualizeFitGMMsLog, echo=FALSE, message=FALSE, cache=TRUE----------

plotFitMM(Koeffler_BM_CebpE_log$pileup, GMMs_list_Koeffler_BM_CebpE_log,
          output_n='figs/Koeffler_BM_CebpE_GMM_ModelVisualization_log', 
          titleName='Koeffler_BM_CebpE_log', model='GMM')



## ----VisualizeFitNBMs, results='hide', message=FALSE, cache=TRUE---------

visualizeFitMMs(X=Koeffler_BM_CebpE, MMs_list=NBMs_list_Koeffler_BM_CebpE, 
                max_k=10, output_n='figs/Koeffler_BM_CebpE_NBM_ModelVisualization', 
                model = 'NBM', titleName='Koeffler_BM_CebpE') 



## ----compFreqTableGMM, warning=FALSE, cache=TRUE, results='hide', echo=FALSE----
compFreq2GMM_Koeffler_BM_CebpE <- getCompFreqTable(Koeffler_BM_CebpE$pileup, k=2, n=3, 
                                                   model='GMM')
compFreq3GMM_Koeffler_BM_CebpE <- getCompFreqTable(Koeffler_BM_CebpE$pileup, k=3, n=3, 
                                                   model='GMM')
compFreq4GMM_Koeffler_BM_CebpE <- getCompFreqTable(Koeffler_BM_CebpE$pileup, k=4, n=3, 
                                                   model='GMM')
compFreq5GMM_Koeffler_BM_CebpE <- getCompFreqTable(Koeffler_BM_CebpE$pileup, k=5, n=3, 
                                                   model='GMM')
compFreq6GMM_Koeffler_BM_CebpE <- getCompFreqTable(Koeffler_BM_CebpE$pileup, k=6, n=3, 
                                                   model='GMM')
compFreq7GMM_Koeffler_BM_CebpE <- getCompFreqTable(Koeffler_BM_CebpE$pileup, k=7, n=3, 
                                                   model='GMM')
compFreq8GMM_Koeffler_BM_CebpE <- getCompFreqTable(Koeffler_BM_CebpE$pileup, k=8, n=3, 
                                                   model='GMM')
compFreq9GMM_Koeffler_BM_CebpE <- getCompFreqTable(Koeffler_BM_CebpE$pileup, k=9, n=3, 
                                                   model='GMM')
compFreq10GMM_Koeffler_BM_CebpE <- getCompFreqTable(Koeffler_BM_CebpE$pileup, k=10, n=3, 
                                                    model='GMM')


## ----compFreqPDFGMM, echo=FALSE, results='hide', cache=TRUE--------------
mapply(function(x, model){
                  input_ <- paste0('compFreq', x, model, '_Koeffler_BM_CebpE')
                  title_ <- paste0('Koeffler_BM_CebpE_CompFreqTable_', x, '_comp_', model)
                  output_ <- paste0('figs/', title_, '.pdf')
                  createPDFTable(get(input_), title_, output_)}, seq(2,10), 'GMM')



## ----compFreqTableGMMLog, warning=FALSE, cache=TRUE, results='hide', echo=FALSE----
compFreq2GMM_Koeffler_BM_CebpE_log <- getCompFreqTable(Koeffler_BM_CebpE_log$pileup, k=2, n=3, 
                                                   model='GMM')
compFreq3GMM_Koeffler_BM_CebpE_log <- getCompFreqTable(Koeffler_BM_CebpE_log$pileup, k=3, n=3, 
                                                   model='GMM')
compFreq4GMM_Koeffler_BM_CebpE_log <- getCompFreqTable(Koeffler_BM_CebpE_log$pileup, k=4, n=3, 
                                                   model='GMM')
compFreq5GMM_Koeffler_BM_CebpE_log <- getCompFreqTable(Koeffler_BM_CebpE_log$pileup, k=5, n=3, 
                                                   model='GMM')
compFreq6GMM_Koeffler_BM_CebpE_log <- getCompFreqTable(Koeffler_BM_CebpE_log$pileup, k=6, n=3, 
                                                   model='GMM')


## ----compFreqPDFGMMLog, echo=FALSE, results='hide', cache=TRUE-----------
mapply(function(x, model){
                  input_ <- paste0('compFreq', x, model, '_Koeffler_BM_CebpE_log')
                  title_ <- paste0('Koeffler_BM_CebpE_CompFreqTable_', x, '_comp_', model)
                  output_ <- paste0('figs/', title_, '_log.pdf')
                  createPDFTable(get(input_), title_, output_)}, seq(2,6), 'GMM')



## ----compFreqTableNBM, warning=FALSE, cache=TRUE, results='hide', echo=FALSE----
compFreq2NBM_Koeffler_BM_CebpE <- getCompFreqTable(Koeffler_BM_CebpE$pileup, k=2, n=3, 
                                                   model='NBM')
compFreq3NBM_Koeffler_BM_CebpE <- getCompFreqTable(Koeffler_BM_CebpE$pileup, k=3, n=3, 
                                                   model='NBM')
compFreq4NBM_Koeffler_BM_CebpE <- getCompFreqTable(Koeffler_BM_CebpE$pileup, k=4, n=3, 
                                                   model='NBM')
compFreq5NBM_Koeffler_BM_CebpE <- getCompFreqTable(Koeffler_BM_CebpE$pileup, k=5, n=3, 
                                                   model='NBM')
#compFreq6NBM_Koeffler_BM_CebpE <- getCompFreqTable(Koeffler_BM_CebpE$pileup, k=6, n=3, 
#                                                   model='NBM')
#compFreq7NBM_Koeffler_BM_CebpE <- getCompFreqTable(Koeffler_BM_CebpE$pileup, k=7, n=3, 
#                                                   model='NBM')
#compFreq8NBM_Koeffler_BM_CebpE <- getCompFreqTable(Koeffler_BM_CebpE$pileup, k=8, n=3, 
#                                                   model='NBM')
#compFreq9NBM_Koeffler_BM_CebpE <- getCompFreqTable(Koeffler_BM_CebpE$pileup, k=9, n=3, 
#                                                   model='NBM')
#compFreq10NBM_Koeffler_BM_CebpE <- getCompFreqTable(Koeffler_BM_CebpE$pileup, k=10, n=3, 
#                                                    model='NBM')


## ----compFreqPDFNBM, echo=FALSE, cache=TRUE------------------------------
mapply(function(x, model){
                  input_ <- paste0('compFreq', x, model, '_Koeffler_BM_CebpE')
                  title_ <- paste0('Koeffler_BM_CebpE_CompFreqTable_', x, '_comp_', model)
                  output_ <- paste0('figs/', title_, '.pdf')
                  createPDFTable(get(input_), title_, output_)}, seq(2,5), 'NBM')


## ----pdfTableCropping, engine='bash'-------------------------------------
# to adjust the margin of the pdf table 
#for f in $(ls Koeffler_BM_CebpE_CompFreqTable_*); do pdfcrop --margins '5 10 5 20' $f $f; done


## ----modelAssessmentGMM, results='hide', cache=TRUE----------------------

getModelAssessment(GMMs_list_Koeffler_BM_CebpE, max_k = 10, 
                   output_n='figs/Koeffler_BM_CebpE_GMM_ModelAssessment',
                   model='GMM', titleName='Koeffler_BM_CebpE') 



## ----modelAssessmentGMMLog, results='hide', cache=TRUE-------------------

getModelAssessment(GMMs_list_Koeffler_BM_CebpE_log, max_k = 10, 
                   output_n='figs/Koeffler_BM_CebpE_GMM_ModelAssessment_log',
                   model='GMM', titleName='Koeffler_BM_CebpE_Log') 



## ----modelAssessmentNB, cache=TRUE---------------------------------------
getModelAssessment(NBMs_list_Koeffler_BM_CebpE, max_k = 10, 
                   output_n='figs/Koeffler_BM_CebpE_NBM_ModelAssessment',
                   model='NBM', titleName='Koeffler_BM_CebpE') 


## ----componentAssignmentGMM, cache=TRUE, results='hide'------------------
assignComponentMMs(Koeffler_BM_CebpE, GMMs_list_Koeffler_BM_CebpE, 
                   output_n=paste0(work_dir,
                    'Output/Koeffler_BM_CebpE_GMM_ModelAssignment'), 
                    model='GMM', sort.comp=TRUE)


## ----componentAssignmentGMMlog, cache=TRUE, results='hide'---------------
assignComponentMMs(Koeffler_BM_CebpE_log, GMMs_list_Koeffler_BM_CebpE_log, 
                   output_n=paste0(work_dir,
                    'Output/Koeffler_BM_CebpE_GMM_ModelAssignment_log'), 
                    model='GMM', sort.comp=TRUE)


## ----componentAssignmentNBM, cache=TRUE, results='hide'------------------
assignComponentMMs(Koeffler_BM_CebpE, NBMs_list_Koeffler_BM_CebpE, 
                   output_n=paste0(work_dir,
                    'Output/Koeffler_BM_CebpE_NBM_ModelAssignment'), 
                   model='NBM', sort.comp=TRUE)


## ----VisualizeCompAssign, echo=FALSE, results='hide',cache=TRUE, include=FALSE----

#list_compSortedFiles <- lapply(2:10, function(x) 
#                         paste0('Koeffler_BM_CebpE_GMM_ModelAssignment_compSorted', x))
#
#lapply(list_compSortedFiles, function(x) visualizeCompAssign(
#                                    bed_f=paste0('ComponentCalls/CebpE/Output/Tables/',x, '.bed'), 
#                                    chrom='chr14', title_f=x, 
#                                    output_f=paste0('ComponentCalls/CebpE/Output/Plots/',x, '.pdf')))

#GMM
visualizeCompAssign(bed_f = paste0(work_dir,
                    'Output/Koeffler_BM_CebpE_GMM_ModelAssignment_compSorted4.bed'),
                    chrom='chr14', title_f = 'Koeffler_BM_CebpE_GMM_ModelAssignment_compSorted4',
                    output_f = 'figs/Koeffler_BM_CebpE_GMM_ModelAssignment_compSorted4.pdf')
# GMM log
visualizeCompAssign(bed_f = paste0(work_dir,
                    'Output/Koeffler_BM_CebpE_GMM_ModelAssignment_log_compSorted4.bed'),
                    chrom='chr14', title_f = 'Koeffler_BM_CebpE_GMM_ModelAssignment_log_ompSorted4',
                    output_f = 'figs/Koeffler_BM_CebpE_GMM_ModelAssignment_log_compSorted4.pdf')

#NBM
visualizeCompAssign(bed_f = paste0(work_dir,
                    'Output/Koeffler_BM_CebpE_NBM_ModelAssignment_compSorted4.bed'),
                    chrom='chr14', title_f = 'Koeffler_BM_CebpE_NBM_ModelAssignment_compSorted4',
                    output_f = 'figs/Koeffler_BM_CebpE_NBM_ModelAssignment_compSorted4.pdf')



## ----StatComponentAssignment, echo=FALSE, results='hide', message=FALSE, cache=TRUE----

#lapply(list_compSortedFiles, function(x) boxplot_compAssignment(
#                                    paste0('ComponentCalls/CebpE/Output/Tables/',x, '.bed'), 
#                                    title_f=x,
#                                    output_f=paste0('ComponentCalls/CebpE/Output/Plots/',x, '_Boxplot.pdf')))

boxplot_compAssignment(bed_f=paste0(work_dir,
                       'Output/Koeffler_BM_CebpE_GMM_ModelAssignment_compSorted4.bed'),
                       title_f = 'Koeffler_BM_CebpE_GMM_ModelAssignment_compSorted4',
                       output_f ='figs/Koeffler_BM_CebpE_GMM_ModelAssignment_compSorted4_Boxplot.pdf')

boxplot_compAssignment(bed_f=paste0(work_dir,
                       'Output/Koeffler_BM_CebpE_GMM_ModelAssignment_log_compSorted4.bed'),
                       title_f = 'Koeffler_BM_CebpE_GMM_ModelAssignment_log_compSorted4',
                       output_f ='figs/Koeffler_BM_CebpE_GMM_ModelAssignment_log_compSorted4_Boxplot.pdf')

boxplot_compAssignment(bed_f=paste0(work_dir,
                       'Output/Koeffler_BM_CebpE_NBM_ModelAssignment_compSorted4.bed'),
                       title_f = 'Koeffler_BM_CebpE_NBM_ModelAssignment_compSorted4',
                       output_f ='figs/Koeffler_BM_CebpE_NBM_ModelAssignment_compSorted4_Boxplot.pdf')




## ----boxplotProfile, cache=TRUE------------------------------------------
Koeffler_BM_CebpE_group1_compSorted4 <- read.csv(sep='\t',paste0(work_dir, 
    'Output/Koeffler_BM_CebpE_GMM_ModelAssignment_log_group1_compSorted4_ProfileMatrix.txt'),
    header=TRUE, row.names=1, check.names=F)
Koeffler_BM_CebpE_group2_compSorted4 <- read.csv(sep='\t',paste0(work_dir, 
    'Output/Koeffler_BM_CebpE_GMM_ModelAssignment_log_group2_compSorted4_ProfileMatrix.txt'),
    header=TRUE, row.names=1, check.names=F)
Koeffler_BM_CebpE_group3_compSorted4 <- read.csv(sep='\t',paste0(work_dir, 
    'Output/Koeffler_BM_CebpE_GMM_ModelAssignment_log_group3_compSorted4_ProfileMatrix.txt'),
    header=TRUE, row.names=1, check.names=F)
Koeffler_BM_CebpE_group4_compSorted4 <- read.csv(sep='\t',paste0(work_dir, 
    'Output/Koeffler_BM_CebpE_GMM_ModelAssignment_log_group4_compSorted4_ProfileMatrix.txt'),
    header=TRUE, row.names=1, check.names=F)
head(Koeffler_BM_CebpE_group1_compSorted4)[,199:200]

pdf('figs/Koeffler_BM_CebpE_BoxplotProfile.pdf', 
    useDingbats=FALSE)
boxplot(Koeffler_BM_CebpE_group1_compSorted4, cex=0.1, col='red', bty='n')
boxplot(Koeffler_BM_CebpE_group2_compSorted4, cex=0.1, col='green', add=T, bty='n')
boxplot(Koeffler_BM_CebpE_group3_compSorted4, cex=0.1, col='yellow', add=T, bty='n')
boxplot(Koeffler_BM_CebpE_group4_compSorted4, cex=0.1, col='blue', add=T, bty='n')
dev.off()


## ------------------------------------------------------------------------
sessionInfo()


## ----knitIt,  message=FALSE, warning=FALSE-------------------------------
library(knitr)
purl("componentAnalysis.Rnw" ) # compile to tex
purl("componentAnalysis.Rnw", documentation = 0) # extract R code only
knit2pdf("componentAnalysis.Rnw")


